### ISSUE TITLE
BUGFIX: app needs a Refresh to run

### ISSUE THREAD

**Issue by korenmiklos** [ceumicrodata/trade-similarity-thin-client#7]
When starting https://respect.microdata.io/, the response is "Loading..." for a loooong time. When hitting refresh, the app loads. This may be due to AWS Lambda timeouts.

**Comment by gaborberei** [comment]
Maybe we should use:

if __name__ == '__main__':
  app.run_server(debug=True)

This is the development environment, maybe it helps.
